hyperparameters:
  RandomForestClassifier:
    n_estimators: [100, 200, 300]
    max_depth: [5, 10, 20]
    max_features: [0.5, 0.7, 1]
    random_state: [42]
    class_weight: ['balanced']

  GradientBoostingClassifier:
    n_estimators: [100, 200, 300]
    max_depth: [5, 10, 20]
    max_features: [0.5, 0.7, 1]
    random_state: [42]

  LogisticRegression:
    C: [0.01, 0.1, 1.0, 10.0]
    penalty: ['l1', 'l2']
    solver: ['liblinear']
    random_state: [42]
    class_weight: ['balanced']

  XGBClassifier:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.2]
    subsample: [ 0.8, 1.0]
    colsample_bytree: [ 0.8, 1.0]
    random_state: [42]
